### ISSUE TITLE
TypeLoadException after adding OrchardCoreContrib.Apis.Swagger

### ISSUE THREAD

**Issue by andreapier** [OrchardCoreContrib/OrchardCoreContrib.Modules#97]
I added `OrchardCoreContrib.Apis.Swagger` to my project and now it crashes during startup with this exception:
```
Unhandled exception. System.TypeLoadException: Method 'AddSourcesAsync' in type 'OrchardCore.Environment.Shell.Configuration.ShellsSettingsSources' from assembly 'OrchardCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
    at Microsoft.Extensions.DependencyInjection.ShellOrchardCoreBuilderExtensions.AddSitesFolder(OrchardCoreBuilder builder)
    at Microsoft.Extensions.DependencyInjection.ShellOrchardCoreBuilderExtensions.AddDataStorage(OrchardCoreBuilder builder)
    at Microsoft.Extensions.DependencyInjection.ServiceExtensions.AddOrchardCms(IServiceCollection services)
    at Program.<Main>$(String[] args) in /src/Identity.Api/Program.cs:line 18
    at Program.<Main>(String[] args)
```
I am running in docker, but I doubt this makes a difference.  
What should I do to fix this issue?

**Comment by hishamco** [comment]
@andreapier I'm not sure if it's from `OCC.Api.Swagger` or something related to OC

Is it working without docker?

**Comment by hishamco** [comment]
Could you try to run `OCC.Modules.Web`?

> /src/Identity.Api/Program.cs:line 18

I don't know what's in there?!!

**Comment by hishamco** [comment]
Closing this while there's no feedback from the author
